apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: citysynergy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: iamcj
            - name: MYSQL_DATABASE
              value: citysynergy
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          emptyDir: {}   # use PVC here later for persistent storage
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: citysynergy
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306

